POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFzZCIsImlkIjoiNjZkNzNiMTdhYTE3OGMwZmU5YzRkZDAwIiwiaWF0IjoxNzI1NDQ5NDI5fQ.rqRP5TvLOFPk_Eh7agD8yiGT6iTss1BAZ7zalVU67_o

{
    "content": "asdasda",
    "important": true
}